= Create GKE Cluster with Terraform

Statements below utilize homebrew on MacOS. Be sure to update the tfvars file with values specific to your setup

== Installations

=== Install Terraform

[source,sh]
----
$ brew install terraform

----

=== Install Google Cloud CLI

Reference: https://cloud.google.com/sdk/docs/install-sdk

[source,sh]
----
$ gcloud init

----

Project id: `solutionsarchitect-01`

Region: `&lt; your-gcloud-region &gt;`

== GCloud Setup

=== Enable Compute and Kubernetes APIs

[source,sh]
----
$ gcloud services enable compute.googleapis.com
$ gcloud services enable container.googleapis.com
----

=== Create service-account for Terraform

[source,sh]
----
$ gcloud iam service-accounts create <your-service-account-name> --display-name=<DISPLAY_NAME>
----

=== Assign Roles

The service-account needs the following project roles to be able to execute the Terraform configuration and create the GKE cluster: 

* roles/compute.viewer
* roles/compute.securityAdmin
* Required if add_cluster_firewall_rules is set to true
* roles/container.clusterAdmin
* roles/container.developer
* roles/iam.serviceAccountAdmin
* roles/iam.serviceAccountUser
* roles/resourcemanager.projectIamAdmin (required if - service_account is set to create)

These roles can be assigned to the service account with the following commands (NOTE: if you get an error running these commands make sure you have rights to create these roles (eg that you are an Owner for the GCP project you're using)):

[source,sh]
----
$ gcloud projects add-iam-policy-binding solutionsarchitect-01 --member serviceAccount:<your-service-account-name>@solutionsarchitect-01.iam.gserviceaccount.com --condition=None --role roles/compute.admin   
                        
$ gcloud projects add-iam-policy-binding solutionsarchitect-01 --member serviceAccount:<your-service-account-name>@solutionsarchitect-01.iam.gserviceaccount.com --condition=None --role roles/iam.serviceAccountUser                             

$ gcloud projects add-iam-policy-binding solutionsarchitect-01 --member serviceAccount:<your-service-account-name>@solutionsarchitect-01.iam.gserviceaccount.com --condition=None --role roles/resourcemanager.projectIamAdmin                             

$ gcloud projects add-iam-policy-binding solutionsarchitect-01 --member serviceAccount:<your-service-account-name>@solutionsarchitect-01.iam.gserviceaccount.com --condition=None --role roles/container.clusterAdmin

$ gcloud projects add-iam-policy-binding solutionsarchitect-01 --member serviceAccount:<your-service-account-name>@solutionsarchitect-01.iam.gserviceaccount.com --condition=None --role roles/compute.viewer

$ gcloud projects add-iam-policy-binding solutionsarchitect-01 --member serviceAccount:<your-service-account-name>@solutionsarchitect-01.iam.gserviceaccount.com --condition=None --role roles/compute.securityAdmin

$ gcloud projects add-iam-policy-binding solutionsarchitect-01 --member serviceAccount:<your-service-account-name>@solutionsarchitect-01.iam.gserviceaccount.com --condition=None --role roles/container.developer

$ gcloud projects add-iam-policy-binding solutionsarchitect-01 --member serviceAccount:<your-service-account-name>@solutionsarchitect-01.iam.gserviceaccount.com --condition=None --role roles/iam.serviceAccountAdmin

$ gcloud projects add-iam-policy-binding solutionsarchitect-01 --member serviceAccount:<your-service-account-name>@solutionsarchitect-01.iam.gserviceaccount.com --condition=None --role roles/resourcemanager.projectIamAdmin
----

If you are asked for a condition you can select 5 - None for this exercise.

=== GCP Authentication

Create JSON key file for the service-account that Terraform will use to authenticate with Google Cloud to create the infrastructure. 

[source,sh]
----
$ gcloud iam service-accounts keys create tf-gke-keyfile.json --iam-account <your-service-account-name>@solutionsarchitect-01.iam.gserviceaccount.com
----

== Terraform

=== Terraform Backend (GCS)

Create a GCS bucket where to store the Terraform state

[source,sh]
----
$ gsutil mb -p solutionsarchitect-01 -c regional -l us-west1 gs://<your-gcs-bucket-name>/
----

Enable versioning in case of accidental deletion or errors:

[source,sh]
----
$ gsutil versioning set on gs://<your-gcs-bucket-name>/
----

Enable read/write permissions on this bucket for our service account:

[source,sh]
----
$ gsutil iam ch serviceAccount:<your-service-account-name>@solutionsarchitect-01.iam.gserviceaccount.com:legacyBucketWriter gs://<your-gcs-bucket-name>/
----

=== Provision Terraform Resources (GKE)
Cluster and node pool will take roughly 5-10 minutes to provision

[source,sh]
----
$ terraform init
$ terraform plan
$ terraform apply
----
